import path from "path";
import { fileURLToPath } from "url";
import { buildConfig } from "payload";
import { sqliteAdapter } from "@payloadcms/db-sqlite";
import { lexicalEditor } from "@payloadcms/richtext-lexical";

// sharp bazı sunucularda native modül sorunu çıkarabiliyor; yüklenemezse
// görsel işleme (crop/resize) kapalı çalışır, uygulama etkilenmez.
const sharp = await import("sharp")
  .then((m) => m.default)
  .catch(() => undefined);

const filename = fileURLToPath(import.meta.url);
const dirname = path.dirname(filename);

export default buildConfig({
  admin: {
    user: "users",
    theme: "light",
    meta: {
      titleSuffix: " · Kumru Köseler",
      title: "Kumru Köseler Panel",
      description: "Kumru Köseler web sitesi yönetim paneli",
      icons: [{ rel: "icon", type: "image/png", url: "/favicon.png" }],
    },
    importMap: {
      baseDir: path.resolve(dirname),
      importMapFile: path.resolve(dirname, "app/(payload)/admin/importMap.js"),
    },
    components: {
      graphics: {
        Logo: "/components/admin/Logo#Logo",
        Icon: "/components/admin/Icon#Icon",
      },
      actions: [
        // "Siteyi Gör" butonu kaldırıldı (daha minimalist üst bar)
        "/components/admin/NavOpener#NavOpener",
      ],
      views: {
        dashboard: {
          Component: "/components/admin/Dashboard#Dashboard",
        },
      },
    },
  },
  editor: lexicalEditor(),
  localization: {
    locales: [
      { label: "Türkçe", code: "tr" },
      { label: "English", code: "en" },
    ],
    defaultLocale: "tr",
    fallback: true,
  },
  collections: [
    {
      slug: "users",
      auth: true,
      admin: { useAsTitle: "email", group: "Ayarlar & Sistem" },
      labels: { singular: "Kullanıcı", plural: "Kullanıcılar" },
      fields: [
        { name: "name", type: "text", label: "Ad Soyad" },
      ],
    },
    {
      slug: "media",
      labels: { singular: "Medya", plural: "Medya Kütüphanesi" },
      access: { read: () => true },
      admin: { group: "Medya & Görseller" },
      upload: {
        staticDir: path.resolve(dirname, "../uploads"),
        mimeTypes: ["image/*", "video/mp4", "video/webm", "application/pdf"],
        ...(sharp ? {} : { crop: false, focalPoint: false }),
      },
      fields: [
        { name: "alt", type: "text", label: "Açıklama (alt metin)", localized: true },
      ],
    },
    {
      slug: "videos",
      labels: { singular: "Video", plural: "Videolar" },
      access: { read: () => true },
      admin: { useAsTitle: "title", defaultColumns: ["title", "source", "published"], group: "Medya & Görseller" },
      fields: [
        { name: "title", type: "text", required: true, localized: true, label: "Başlık" },
        { name: "description", type: "textarea", localized: true, label: "Açıklama" },
        {
          name: "source",
          type: "select",
          required: true,
          defaultValue: "youtube",
          label: "Kaynak",
          options: [
            { label: "YouTube", value: "youtube" },
            { label: "Dosya (mp4)", value: "upload" },
          ],
        },
        {
          name: "youtubeUrl",
          type: "text",
          label: "YouTube Linki",
          admin: { condition: (data) => data?.source === "youtube" },
        },
        {
          name: "videoFile",
          type: "upload",
          relationTo: "media",
          label: "Video Dosyası",
          admin: { condition: (data) => data?.source === "upload" },
        },
        { name: "thumbnail", type: "upload", relationTo: "media", label: "Kapak Görseli" },
        { name: "published", type: "checkbox", defaultValue: true, label: "Yayında" },
        { name: "order", type: "number", defaultValue: 0, label: "Sıra" },
      ],
    },
    {
      slug: "spiritual-sessions",
      labels: { singular: "Spiritüel Seans", plural: "Spiritüel Seanslar" },
      access: { read: () => true },
      admin: { useAsTitle: "title", defaultColumns: ["title", "duration", "price", "order"], group: "Hizmetler & Programlar" },
      fields: [
        { name: "title", type: "text", required: true, localized: true, label: "Seans Adı" },
        { name: "description", type: "textarea", localized: true, label: "Açıklama" },
        { name: "duration", type: "text", localized: true, label: "Süre" },
        { name: "price", type: "text", label: "Fiyat" },
        { name: "order", type: "number", defaultValue: 0, label: "Sıra" },
      ],
    },
    {
      slug: "coaching-services",
      labels: { singular: "Koçluk Hizmeti", plural: "Koçluk Hizmetleri" },
      access: { read: () => true },
      admin: { useAsTitle: "title", defaultColumns: ["title", "duration", "order"], group: "Hizmetler & Programlar" },
      fields: [
        { name: "key", type: "text", required: true, unique: true, label: "Sistem Anahtarı", admin: { description: "Sayfa eşlemesi için - değiştirmeyin (örn. oneOnOne)" } },
        { name: "title", type: "text", required: true, localized: true, label: "Hizmet Adı" },
        { name: "shortDesc", type: "textarea", localized: true, label: "Kısa Açıklama" },
        { name: "fullDesc", type: "textarea", localized: true, label: "Uzun Açıklama" },
        { name: "duration", type: "text", localized: true, label: "Süre" },
        {
          name: "features",
          type: "array",
          localized: true,
          label: "Özellikler",
          fields: [{ name: "feature", type: "text", label: "Özellik" }],
        },
        { name: "order", type: "number", defaultValue: 0, label: "Sıra" },
      ],
    },
    {
      slug: "programs",
      labels: { singular: "Program", plural: "Programlar" },
      access: { read: () => true },
      admin: { useAsTitle: "title", defaultColumns: ["title", "duration", "order"], group: "Hizmetler & Programlar" },
      fields: [
        { name: "key", type: "text", required: true, unique: true, label: "Sistem Anahtarı", admin: { description: "Sayfa eşlemesi için - değiştirmeyin (örn. oneOnOne)" } },
        { name: "title", type: "text", required: true, localized: true, label: "Program Adı" },
        { name: "subtitle", type: "text", localized: true, label: "Alt Başlık" },
        { name: "duration", type: "text", localized: true, label: "Süre" },
        { name: "sessions", type: "text", localized: true, label: "Seans Tipi" },
        { name: "description", type: "textarea", localized: true, label: "Açıklama" },
        {
          name: "includes",
          type: "array",
          localized: true,
          label: "Dahil Olanlar",
          fields: [{ name: "item", type: "text", label: "Madde" }],
        },
        { name: "popular", type: "checkbox", defaultValue: false, label: "En Popüler" },
        { name: "hotelIncluded", type: "checkbox", defaultValue: false, label: "Otel Konaklamalı" },
        { name: "order", type: "number", defaultValue: 0, label: "Sıra" },
      ],
    },
    {
      slug: "events",
      labels: { singular: "Etkinlik", plural: "Etkinlikler" },
      access: { read: () => true },
      admin: { useAsTitle: "title", defaultColumns: ["title", "dateText", "isPast", "order"], group: "Hizmetler & Programlar" },
      fields: [
        { name: "title", type: "text", required: true, localized: true, label: "Etkinlik Adı" },
        { name: "description", type: "textarea", localized: true, label: "Açıklama" },
        { name: "dateText", type: "text", localized: true, label: "Tarih (örn. 15 Mart 2025)" },
        { name: "time", type: "text", label: "Saat (örn. 21:00 - 22:00)" },
        { name: "isPast", type: "checkbox", defaultValue: false, label: "Gerçekleşti" },
        { name: "order", type: "number", defaultValue: 0, label: "Sıra" },
      ],
    },
    {
      slug: "faqs",
      labels: { singular: "SSS", plural: "Sık Sorulan Sorular" },
      access: { read: () => true },
      admin: { useAsTitle: "question", group: "Kaynaklar & Blog" },
      fields: [
        { name: "question", type: "text", required: true, localized: true, label: "Soru" },
        { name: "answer", type: "textarea", localized: true, label: "Cevap" },
        { name: "order", type: "number", defaultValue: 0, label: "Sıra" },
      ],
    },
    {
      slug: "contact-messages",
      labels: { singular: "İletişim Mesajı", plural: "İletişim Mesajları" },
      access: {
        read: ({ req: { user } }) => Boolean(user),
        create: () => true,
        update: () => false,
        delete: ({ req: { user } }) => Boolean(user),
      },
      admin: {
        useAsTitle: "name",
        defaultColumns: ["name", "email", "subject", "createdAt"],
        description: "Web sitesindeki iletişim formundan gelen mesajlar",
        group: "Etkileşim",
      },
      fields: [
        { name: "name", type: "text", required: true, label: "Ad Soyad" },
        { name: "email", type: "email", required: true, label: "E-posta" },
        { name: "phone", type: "text", label: "Telefon" },
        { name: "subject", type: "text", label: "Konu" },
        { name: "message", type: "textarea", required: true, label: "Mesaj" },
      ],
    },
    {
      slug: "resource-items",
      labels: { singular: "Kaynak", plural: "Kaynaklar (E-Kitap/Video)" },
      access: { read: () => true },
      admin: { useAsTitle: "title", defaultColumns: ["title", "type", "category", "order"], group: "Kaynaklar & Blog" },
      fields: [
        { name: "title", type: "text", required: true, localized: true, label: "Başlık" },
        { name: "description", type: "textarea", localized: true, label: "Açıklama" },
        {
          name: "type",
          type: "select",
          defaultValue: "PDF",
          label: "Tür",
          options: [
            { label: "PDF", value: "PDF" },
            { label: "Video", value: "Video" },
            { label: "Ses", value: "Ses" },
          ],
        },
        { name: "category", type: "text", localized: true, label: "Kategori" },
        { name: "order", type: "number", defaultValue: 0, label: "Sıra" },
      ],
    },
    {
      slug: "blog-posts",
      labels: { singular: "Blog Yazısı", plural: "Blog Yazıları" },
      access: { read: () => true },
      admin: { useAsTitle: "title", defaultColumns: ["title", "category", "readTime", "order"], group: "Kaynaklar & Blog" },
      fields: [
        { name: "title", type: "text", required: true, localized: true, label: "Başlık" },
        { name: "excerpt", type: "textarea", localized: true, label: "Özet" },
        { name: "category", type: "text", localized: true, label: "Kategori" },
        { name: "readTime", type: "text", localized: true, label: "Okuma Süresi" },
        { name: "order", type: "number", defaultValue: 0, label: "Sıra" },
      ],
    },
    {
      slug: "tips",
      labels: { singular: "İpucu", plural: "Günlük İpuçları" },
      access: { read: () => true },
      admin: { useAsTitle: "title", defaultColumns: ["title", "order"], group: "Kaynaklar & Blog" },
      fields: [
        { name: "title", type: "text", required: true, localized: true, label: "Başlık" },
        { name: "tip", type: "textarea", localized: true, label: "İpucu Metni" },
        { name: "order", type: "number", defaultValue: 0, label: "Sıra" },
      ],
    },
    {
      slug: "testimonials",
      labels: { singular: "Danışan Yorumu", plural: "Danışan Yorumları" },
      access: { read: () => true },
      admin: { useAsTitle: "name", defaultColumns: ["name", "rating", "order"], group: "Etkileşim" },
      fields: [
        { name: "name", type: "text", required: true, label: "Ad Soyad" },
        { name: "text", type: "textarea", required: true, localized: true, label: "Yorum" },
        { name: "rating", type: "number", defaultValue: 5, min: 1, max: 5, label: "Puan (1-5)" },
        { name: "order", type: "number", defaultValue: 0, label: "Sıra" },
      ],
    },
    {
      slug: "members",
      auth: {
        tokenExpiration: 60 * 60 * 24 * 30,
        verify: false,
        maxLoginAttempts: 5,
        lockTime: 10 * 60 * 1000,
      },
      labels: { singular: "Üye", plural: "Üyeler" },
      admin: {
        useAsTitle: "email",
        defaultColumns: ["name", "email", "membershipTier", "membershipExpiresAt"],
        group: "Üyeler & Satış",
        description: "Web sitesine kayıt olan danışanlar (admin paneline giremezler).",
      },
      access: {
        create: () => true, // herkes kayıt olabilir
        read: ({ req: { user } }) => Boolean(user),
        update: ({ req: { user } }) => Boolean(user),
        delete: ({ req: { user } }) => Boolean(user),
      },
      fields: [
        { name: "name", type: "text", required: true, label: "Ad Soyad" },
        {
          name: "membershipTier",
          type: "select",
          defaultValue: "free",
          label: "Üyelik Seviyesi",
          options: [
            { label: "Ücretsiz", value: "free" },
            { label: "Premium", value: "premium" },
            { label: "VIP", value: "vip" },
          ],
          admin: { description: "Ödeme entegrasyonu bağlanana kadar buradan elle yükseltilebilir." },
        },
        { name: "membershipExpiresAt", type: "date", label: "Üyelik Bitiş Tarihi", admin: { description: "Boşsa süresiz." } },
        { name: "phone", type: "text", label: "Telefon" },
      ],
    },
    {
      slug: "membership-plans",
      labels: { singular: "Üyelik Planı", plural: "Üyelik Planları" },
      access: { read: () => true },
      admin: { useAsTitle: "name", defaultColumns: ["name", "tier", "price", "order"], group: "Üyeler & Satış" },
      fields: [
        { name: "name", type: "text", required: true, localized: true, label: "Plan Adı" },
        {
          name: "tier",
          type: "select",
          required: true,
          defaultValue: "free",
          label: "Seviye",
          options: [
            { label: "Ücretsiz", value: "free" },
            { label: "Premium", value: "premium" },
            { label: "VIP", value: "vip" },
          ],
        },
        { name: "price", type: "text", localized: true, label: "Fiyat (görünen)", admin: { description: "örn. ₺499 / ay veya Ücretsiz — dile göre değişir" } },
        { name: "priceAmount", type: "number", label: "Fiyat (sayı, kuruş değil TL)", admin: { description: "Ödeme için; örn. 499" } },
        { name: "interval", type: "select", defaultValue: "monthly", label: "Periyot", options: [
          { label: "Aylık", value: "monthly" },
          { label: "Yıllık", value: "yearly" },
          { label: "Tek seferlik / süresiz", value: "once" },
        ] },
        { name: "features", type: "array", localized: true, label: "Özellikler", fields: [{ name: "item", type: "text", label: "Özellik" }] },
        { name: "highlighted", type: "checkbox", defaultValue: false, label: "Öne çıkan plan" },
        { name: "order", type: "number", defaultValue: 0, label: "Sıra" },
      ],
    },
    {
      slug: "courses",
      labels: { singular: "Program", plural: "İlerlemeli Programlar" },
      access: { read: () => true },
      admin: { useAsTitle: "title", defaultColumns: ["title", "requiredTier", "unlockRule", "order"], group: "Üyeler & Satış" },
      fields: [
        { name: "title", type: "text", required: true, localized: true, label: "Program Adı" },
        { name: "slug", type: "text", required: true, unique: true, label: "URL (slug)", admin: { description: "örn. nova-vera-yolculugu" } },
        { name: "description", type: "textarea", localized: true, label: "Açıklama" },
        { name: "coverImage", type: "upload", relationTo: "media", label: "Kapak Görseli" },
        {
          name: "requiredTier",
          type: "select",
          defaultValue: "premium",
          label: "Gereken Üyelik",
          options: [
            { label: "Ücretsiz (herkes)", value: "free" },
            { label: "Premium", value: "premium" },
            { label: "VIP", value: "vip" },
          ],
        },
        {
          name: "unlockRule",
          type: "select",
          defaultValue: "complete",
          label: "Aşama Açılma Kuralı",
          options: [
            { label: "Tamamlayınca açılır (sırayla)", value: "complete" },
            { label: "Zamana bağlı (drip - her gün 1 aşama)", value: "drip" },
            { label: "Kumru manuel açar", value: "manual" },
            { label: "Hepsi açık (kilitsiz)", value: "open" },
          ],
          admin: { description: "İlerlemeli program mantığı. 'Tamamlayınca' = danışan hızlı geçemez." },
        },
        { name: "published", type: "checkbox", defaultValue: true, label: "Yayında" },
        { name: "order", type: "number", defaultValue: 0, label: "Sıra" },
      ],
    },
    {
      slug: "program-stages",
      labels: { singular: "Program Aşaması", plural: "Program Aşamaları" },
      access: { read: ({ req: { user } }) => Boolean(user) }, // içerik gizli; sayfa /api/my üzerinden kilit kontrollü servis edilir
      admin: { useAsTitle: "title", defaultColumns: ["title", "program", "order"], group: "Üyeler & Satış" },
      fields: [
        { name: "program", type: "relationship", relationTo: "courses", required: true, label: "Program" },
        { name: "order", type: "number", required: true, defaultValue: 1, label: "Sıra No" },
        { name: "title", type: "text", required: true, localized: true, label: "Aşama Başlığı" },
        { name: "summary", type: "textarea", localized: true, label: "Kısa Özet (kilitliyken de görünür)" },
        { name: "content", type: "textarea", localized: true, label: "İçerik (metin)" },
        { name: "video", type: "upload", relationTo: "media", label: "Video / Ses" },
        { name: "estimatedMinutes", type: "number", label: "Tahmini süre (dk)" },
      ],
    },
    {
      slug: "enrollments",
      labels: { singular: "Program Kaydı", plural: "Program Kayıtları" },
      access: {
        read: ({ req: { user } }) => Boolean(user),
        create: ({ req: { user } }) => Boolean(user),
        update: ({ req: { user } }) => Boolean(user),
      },
      admin: {
        useAsTitle: "id",
        defaultColumns: ["member", "program", "currentStage", "updatedAt"],
        group: "Üyeler & Satış",
        description: "Üyelerin programlardaki ilerlemesi.",
      },
      fields: [
        { name: "member", type: "relationship", relationTo: "members", required: true, label: "Üye" },
        { name: "program", type: "relationship", relationTo: "courses", required: true, label: "Program" },
        { name: "completedStages", type: "number", hasMany: true, label: "Tamamlanan Aşama Sıraları", admin: { description: "Tamamlanan aşamaların sıra numaraları." } },
        { name: "currentStage", type: "number", defaultValue: 1, label: "Mevcut Aşama" },
        { name: "status", type: "select", defaultValue: "active", options: [
          { label: "Devam ediyor", value: "active" },
          { label: "Tamamlandı", value: "completed" },
        ] },
      ],
    },
  ],
  globals: [
    {
      slug: "site-settings",
      label: "Site Ayarları",
      admin: { group: "Ayarlar & Sistem" },
      access: { read: () => true },
      fields: [
        { name: "email", type: "text", label: "E-posta", defaultValue: "kumrukoseler@gmail.com" },
        { name: "phone", type: "text", label: "Telefon", defaultValue: "+90 534 367 56 69" },
        { name: "whatsapp", type: "text", label: "WhatsApp Numarası (link için)", defaultValue: "905343675669" },
        { name: "address", type: "textarea", localized: true, label: "Adres", defaultValue: "Akmerkez Residens, Kültür, Nisbetiye Cd, 34100 Beşiktaş/İstanbul" },
        { name: "hours", type: "text", localized: true, label: "Çalışma Saatleri", defaultValue: "Pazartesi - Cumartesi: 09:00 - 19:00" },
        { name: "instagram", type: "text", label: "Instagram URL", defaultValue: "https://www.instagram.com/kumrukoseler/" },
        { name: "youtube", type: "text", label: "YouTube URL", defaultValue: "https://www.youtube.com/@kumrukoseler9055" },
        { name: "logo", type: "upload", relationTo: "media", label: "Logo (koyu)" },
        { name: "logoWhite", type: "upload", relationTo: "media", label: "Logo (beyaz - footer)" },
        { name: "favicon", type: "upload", relationTo: "media", label: "Favicon" },
      ],
    },
    {
      slug: "page-images",
      label: "Sayfa Arka Plan Görselleri",
      admin: { group: "Medya & Görseller" },
      access: { read: () => true },
      fields: [
        { name: "servicesBg", type: "upload", relationTo: "media", label: "Hizmetler Arka Plan" },
        { name: "mediaBg", type: "upload", relationTo: "media", label: "Medya Arka Plan" },
        { name: "programsBg", type: "upload", relationTo: "media", label: "Programlar Arka Plan" },
        { name: "resourcesBg", type: "upload", relationTo: "media", label: "Kaynaklar Arka Plan" },
        { name: "contactBg", type: "upload", relationTo: "media", label: "İletişim Arka Plan" },
        { name: "novaVeraBg", type: "upload", relationTo: "media", label: "Nova Vera Arka Plan" },
      ],
    },
    {
      slug: "about",
      label: "Hakkımda Sayfası",
      admin: { group: "Sayfa İçerikleri" },
      access: { read: () => true },
      fields: [
        { name: "profileImage", type: "upload", relationTo: "media", label: "Profil Fotoğrafı" },
        { name: "subtitle", type: "text", localized: true, label: "Üst Başlık" },
        { name: "title", type: "text", localized: true, label: "Başlık" },
        { name: "name", type: "text", localized: true, label: "İsim" },
        { name: "heroDescription", type: "textarea", localized: true, label: "Giriş Açıklama 1" },
        { name: "heroDescription2", type: "textarea", localized: true, label: "Giriş Açıklama 2" },
        { name: "appointment", type: "text", localized: true, label: "Randevu Buton" },
        { name: "mediaButton", type: "text", localized: true, label: "Medya Buton" },
        { name: "storyTitle", type: "text", localized: true, label: "Hikaye Başlığı" },
        { name: "story1", type: "textarea", localized: true, label: "Hikaye 1" },
        { name: "story2", type: "textarea", localized: true, label: "Hikaye 2" },
        { name: "story3", type: "textarea", localized: true, label: "Hikaye 3" },
        { name: "story4", type: "textarea", localized: true, label: "Hikaye 4" },
        { name: "valuesTitle", type: "text", localized: true, label: "Değerler Başlığı" },
        { name: "valuesDescription", type: "textarea", localized: true, label: "Değerler Açıklaması" },
        {
          name: "values",
          type: "group",
          label: "Değerler",
          fields: [
            {
              name: "empathy",
              type: "group",
              label: "Empati",
              fields: [
                { name: "title", type: "text", localized: true, label: "Başlık" },
                { name: "description", type: "textarea", localized: true, label: "Açıklama" },
              ],
            },
            {
              name: "honesty",
              type: "group",
              label: "Dürüstlük",
              fields: [
                { name: "title", type: "text", localized: true, label: "Başlık" },
                { name: "description", type: "textarea", localized: true, label: "Açıklama" },
              ],
            },
            {
              name: "transformation",
              type: "group",
              label: "Dönüşüm",
              fields: [
                { name: "title", type: "text", localized: true, label: "Başlık" },
                { name: "description", type: "textarea", localized: true, label: "Açıklama" },
              ],
            },
            {
              name: "excellence",
              type: "group",
              label: "Mükemmellik",
              fields: [
                { name: "title", type: "text", localized: true, label: "Başlık" },
                { name: "description", type: "textarea", localized: true, label: "Açıklama" },
              ],
            },
          ],
        },
        { name: "certificationsTitle", type: "text", localized: true, label: "Sertifikalar Başlığı" },
        {
          name: "certifications",
          type: "array",
          localized: true,
          label: "Sertifikalar",
          fields: [
            { name: "title", type: "text", label: "Sertifika" },
            { name: "organization", type: "text", label: "Kurum" },
            { name: "year", type: "text", label: "Yıl" },
          ],
        },
        { name: "journeyTitle", type: "text", localized: true, label: "Yolculuk Başlığı" },
        {
          name: "timeline",
          type: "array",
          localized: true,
          label: "Zaman Çizelgesi",
          fields: [
            { name: "year", type: "text", label: "Yıl" },
            { name: "title", type: "text", label: "Başlık" },
            { name: "description", type: "textarea", label: "Açıklama" },
          ],
        },
        { name: "spiritualTitle", type: "text", localized: true, label: "Spiritüel Başlık" },
        { name: "spiritual1", type: "textarea", localized: true, label: "Spiritüel 1" },
        { name: "spiritual2", type: "textarea", localized: true, label: "Spiritüel 2" },
        { name: "spiritual3", type: "textarea", localized: true, label: "Spiritüel 3" },
        {
          name: "spiritualApproaches",
          type: "array",
          localized: true,
          label: "Spiritüel Yaklaşımlar",
          fields: [{ name: "item", type: "text", label: "Yaklaşım" }],
        },
        { name: "ctaTitle", type: "text", localized: true, label: "CTA Başlık" },
        { name: "ctaDescription", type: "textarea", localized: true, label: "CTA Açıklama" },
        { name: "ctaButton", type: "text", localized: true, label: "CTA Buton" },
      ],
    },
    {
      slug: "nova-vera",
      label: "Nova Vera Sayfası",
      admin: { group: "Sayfa İçerikleri" },
      access: { read: () => true },
      fields: [
        { name: "brand", type: "text", localized: true, label: "Marka Adı" },
        { name: "tagline", type: "textarea", localized: true, label: "Slogan" },
        { name: "intro", type: "array", localized: true, label: "Giriş Paragrafları", fields: [{ name: "text", type: "textarea", label: "Paragraf" }] },
        { name: "introQuestion", type: "text", localized: true, label: "Giriş Sorusu" },
        { name: "introAnswer", type: "textarea", localized: true, label: "Giriş Cevabı" },
        { name: "whatTitle", type: "text", localized: true, label: "Nedir Başlığı" },
        { name: "what", type: "array", localized: true, label: "Nedir Paragrafları", fields: [{ name: "text", type: "textarea", label: "Paragraf" }] },
        { name: "whatQuestion", type: "textarea", localized: true, label: "Nedir Sorusu" },
        { name: "journeyTitle", type: "text", localized: true, label: "Yolculuk Başlığı" },
        { name: "journey", type: "array", localized: true, label: "Yolculuk Paragrafları", fields: [{ name: "text", type: "textarea", label: "Paragraf" }] },
        { name: "journeyHighlight", type: "textarea", localized: true, label: "Yolculuk Vurgu" },
        { name: "includesTitle", type: "text", localized: true, label: "İçerik Başlığı" },
        { name: "includesIntro", type: "textarea", localized: true, label: "İçerik Giriş" },
        { name: "includes", type: "array", localized: true, label: "İçerik Maddeleri", fields: [{ name: "item", type: "text", label: "Madde" }] },
        { name: "includesNote", type: "textarea", localized: true, label: "İçerik Notu" },
        { name: "outcomesTitle", type: "text", localized: true, label: "Kazanımlar Başlığı" },
        { name: "outcomes", type: "array", localized: true, label: "Kazanımlar", fields: [{ name: "item", type: "text", label: "Madde" }] },
        { name: "outcomesFinal", type: "textarea", localized: true, label: "Kazanımlar Kapanış" },
        { name: "outcomesNote", type: "textarea", localized: true, label: "Kazanımlar Notu" },
        { name: "notSessionTitle", type: "text", localized: true, label: "Seans Değil Başlığı" },
        { name: "notSession", type: "array", localized: true, label: "Seans Değil Paragrafları", fields: [{ name: "text", type: "textarea", label: "Paragraf" }] },
        { name: "whoTitle", type: "text", localized: true, label: "Kimler İçin Başlığı" },
        { name: "whoIntro", type: "textarea", localized: true, label: "Kimler İçin Giriş" },
        { name: "who", type: "array", localized: true, label: "Kimler İçin Maddeleri", fields: [{ name: "item", type: "text", label: "Madde" }] },
        { name: "whoOutro", type: "textarea", localized: true, label: "Kimler İçin Kapanış" },
        { name: "whoNote", type: "textarea", localized: true, label: "Kimler İçin Notu" },
        { name: "firstStepTitle", type: "text", localized: true, label: "İlk Adım Başlığı" },
        { name: "firstStep", type: "array", localized: true, label: "İlk Adım Paragrafları", fields: [{ name: "text", type: "textarea", label: "Paragraf" }] },
        { name: "quote", type: "textarea", localized: true, label: "Alıntı" },
        { name: "ctaButton", type: "text", localized: true, label: "CTA Buton" },
      ],
    },
    {
      slug: "media-content",
      label: "Medya Sayfası",
      admin: { group: "Sayfa İçerikleri" },
      access: { read: () => true },
      fields: [
        { name: "subtitle", type: "text", localized: true, label: "Üst Başlık" },
        { name: "title", type: "text", localized: true, label: "Başlık" },
        { name: "titleHighlight", type: "text", localized: true, label: "Başlık Vurgu" },
        { name: "description", type: "textarea", localized: true, label: "Açıklama" },
        { name: "featuredTitle", type: "text", localized: true, label: "Öne Çıkan Başlık" },
        {
          name: "mediaItems",
          type: "group",
          label: "Öne Çıkan Medya",
          fields: [
            {
              name: "magazine",
              type: "group",
              label: "Dergi",
              fields: [
                { name: "image", type: "upload", relationTo: "media", label: "Görsel" },
                { name: "title", type: "text", localized: true, label: "Başlık" },
                { name: "subtitle", type: "text", localized: true, label: "Alt Başlık" },
                { name: "date", type: "text", localized: true, label: "Tarih" },
                { name: "description", type: "textarea", localized: true, label: "Açıklama" },
              ],
            },
            {
              name: "award",
              type: "group",
              label: "Ödül",
              fields: [
                { name: "image", type: "upload", relationTo: "media", label: "Görsel" },
                { name: "title", type: "text", localized: true, label: "Başlık" },
                { name: "subtitle", type: "text", localized: true, label: "Alt Başlık" },
                { name: "date", type: "text", localized: true, label: "Tarih" },
                { name: "description", type: "textarea", localized: true, label: "Açıklama" },
              ],
            },
          ],
        },
        { name: "quotesTitle", type: "text", localized: true, label: "Alıntılar Başlığı" },
        {
          name: "quotes",
          type: "array",
          localized: true,
          label: "Basından Alıntılar",
          fields: [
            { name: "quote", type: "textarea", label: "Alıntı" },
            { name: "source", type: "text", label: "Kaynak" },
          ],
        },
        { name: "awardsTitle", type: "text", localized: true, label: "Ödüller Başlığı" },
        {
          name: "awards",
          type: "array",
          localized: true,
          label: "Ödüller & Başarılar",
          fields: [
            { name: "title", type: "text", label: "Ödül" },
            { name: "organization", type: "text", label: "Kurum" },
            { name: "year", type: "text", label: "Yıl" },
          ],
        },
        { name: "instagramTitle", type: "text", localized: true, label: "Instagram Başlığı" },
        { name: "instagramDescription", type: "textarea", localized: true, label: "Instagram Açıklaması" },
        { name: "followInstagram", type: "text", localized: true, label: "Instagram Takip Buton" },
        {
          name: "instagramPosts",
          type: "array",
          label: "Instagram Gönderileri",
          fields: [
            { name: "image", type: "upload", relationTo: "media", label: "Görsel" },
            { name: "link", type: "text", label: "Gönderi Linki" },
          ],
        },
        { name: "ctaTitle", type: "text", localized: true, label: "CTA Başlık" },
        { name: "ctaDescription", type: "textarea", localized: true, label: "CTA Açıklama" },
        { name: "ctaButton", type: "text", localized: true, label: "CTA Buton" },
      ],
    },
    {
      slug: "hero",
      label: "Ana Sayfa - Hero",
      admin: { group: "Sayfa İçerikleri" },
      access: { read: () => true },
      fields: [
        { name: "badge", type: "text", localized: true, label: "Üst Rozet" },
        { name: "title1", type: "text", localized: true, label: "Başlık 1. Satır" },
        { name: "title2", type: "text", localized: true, label: "Başlık 2. Satır" },
        { name: "title3", type: "text", localized: true, label: "Başlık 3. Satır" },
        { name: "description", type: "textarea", localized: true, label: "Açıklama" },
        { name: "cta1", type: "text", localized: true, label: "Birincil Buton" },
        { name: "cta2", type: "text", localized: true, label: "İkincil Buton" },
        { name: "googleReview", type: "text", localized: true, label: "Google Yorum Metni" },
        {
          name: "stats",
          type: "group",
          label: "İstatistikler",
          fields: [
            { name: "clients", type: "text", localized: true, label: "Mutlu Danışan (etiket)" },
            { name: "experience", type: "text", localized: true, label: "Yıl Deneyim (etiket)" },
            { name: "satisfaction", type: "text", localized: true, label: "Memnuniyet (etiket)" },
          ],
        },
      ],
    },
    {
      slug: "chatbot",
      label: "Chatbot Ayarları",
      admin: { group: "Ayarlar & Sistem" },
      access: { read: () => true },
      fields: [
        {
          name: "systemPrompt",
          type: "textarea",
          label: "Sistem Promptu",
          admin: {
            description: "Chatbot'un kimliği, hizmet listesi ve kuralları. Değişiklik sonrası bot otomatik güncellenir.",
            rows: 30,
          },
        },
      ],
    },
    {
      slug: "integrations",
      label: "Entegrasyonlar",
      admin: {
        group: "Ayarlar & Sistem",
        description: "Ödeme, e-posta, SMS ve AI servis anahtarları. Gizli anahtarlar maskelidir; yalnızca yöneticiler görebilir. Güvenlik için .env'de tanımlıysa o değer önceliklidir.",
      },
      // Gizli anahtarlar içerir — yalnızca giriş yapmış yönetici okuyabilir/yazabilir.
      access: {
        read: ({ req: { user } }) => Boolean(user),
        update: ({ req: { user } }) => Boolean(user),
      },
      fields: [
        {
          name: "paymentProvider",
          type: "select",
          label: "Aktif Ödeme Sağlayıcı",
          defaultValue: "iyzico",
          options: [
            { label: "İyzico (TL / taksit)", value: "iyzico" },
            { label: "Stripe (döviz / yurt dışı)", value: "stripe" },
            { label: "İkisi de", value: "both" },
          ],
          admin: { description: "Ana ödeme yöntemi. 'İkisi de' seçilirse müşteri ödeme adımında seçebilir." },
        },
        {
          type: "collapsible",
          label: "İyzico",
          admin: { initCollapsed: true },
          fields: [
            { name: "iyzicoTestMode", type: "checkbox", label: "Test modu (sandbox)", defaultValue: true },
            { name: "iyzicoApiKey", type: "text", label: "İyzico API Key", admin: { components: { Field: "/components/admin/MaskedField#MaskedField" }, description: "🔒 Gizli" } },
            { name: "iyzicoSecretKey", type: "text", label: "İyzico Secret Key", admin: { components: { Field: "/components/admin/MaskedField#MaskedField" }, description: "🔒 Gizli" } },
          ],
        },
        {
          type: "collapsible",
          label: "Stripe",
          admin: { initCollapsed: true },
          fields: [
            { name: "stripeTestMode", type: "checkbox", label: "Test modu", defaultValue: true },
            { name: "stripePublishableKey", type: "text", label: "Stripe Publishable Key", admin: { description: "Herkese açık anahtar (pk_...)" } },
            { name: "stripeSecretKey", type: "text", label: "Stripe Secret Key", admin: { components: { Field: "/components/admin/MaskedField#MaskedField" }, description: "🔒 Gizli (sk_...)" } },
            { name: "stripeWebhookSecret", type: "text", label: "Stripe Webhook Secret", admin: { components: { Field: "/components/admin/MaskedField#MaskedField" }, description: "🔒 Gizli (whsec_...)" } },
          ],
        },
        {
          type: "collapsible",
          label: "OpenAI (Chatbot / Kumru AI)",
          admin: { initCollapsed: true },
          fields: [
            { name: "openaiApiKey", type: "text", label: "OpenAI API Key", admin: { components: { Field: "/components/admin/MaskedField#MaskedField" }, description: "🔒 Gizli (sk-...)" } },
          ],
        },
        {
          type: "collapsible",
          label: "E-posta",
          admin: { initCollapsed: true },
          fields: [
            { name: "emailProvider", type: "select", label: "Sağlayıcı", defaultValue: "resend", options: [
              { label: "Resend", value: "resend" },
              { label: "Postmark", value: "postmark" },
              { label: "SMTP", value: "smtp" },
            ] },
            { name: "emailFrom", type: "text", label: "Gönderen adresi", admin: { description: "örn. Kumru Köseler <info@kumrukoseler.com>" } },
            { name: "emailApiKey", type: "text", label: "E-posta API Key", admin: { components: { Field: "/components/admin/MaskedField#MaskedField" }, description: "🔒 Gizli" } },
          ],
        },
        {
          type: "collapsible",
          label: "SMS (NetGSM)",
          admin: { initCollapsed: true },
          fields: [
            { name: "netgsmUser", type: "text", label: "NetGSM Kullanıcı" },
            { name: "netgsmPassword", type: "text", label: "NetGSM Şifre", admin: { components: { Field: "/components/admin/MaskedField#MaskedField" }, description: "🔒 Gizli" } },
            { name: "netgsmHeader", type: "text", label: "Mesaj Başlığı (onaylı)" },
          ],
        },
      ],
    },
  ],
  secret: process.env.PAYLOAD_SECRET || "kumru-dev-secret-degistir",
  db: sqliteAdapter({
    client: {
      url: process.env.DATABASE_URI || "file:./kumru.db",
    },
  }),
  sharp,
  typescript: {
    outputFile: path.resolve(dirname, "payload-types.ts"),
  },
});
